### PR TITLE
- `is_complete_terms()` now requires same number of duplicate copies.

### PR DESCRIPTION
**Pull request by joethorley**

### CODE REVIEW

**Review by krlmlr — COMMENTED** [review]
I wonder if we should prefer "positive" formulations like `is_complete_terms()`, and also define a new level of perfection for complete and unique terms.

**Comment by joethorley** [comment]
I was mimicking base R naming like `is.unsorted()` but it is kind of counter intuitive

**Comment by joethorley** [comment]
Not sure what you mean by perfection tho?

**Comment by joethorley** [comment]
No need as use chk_unique()

**Pull request merged**
